name: worker_manager
version: 7.2.2
description: The worker_manager allows you to manage CPU-intensive calculations across isolates
homepage: "https://github.com/Renesanse/worker_manager"

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  async: ^2.11.0
  collection: ^1.17.1
  meta: ^1.9.1

dev_dependencies:
  test: ^1.24.3

